export const EVENT_PRESET_FIXTURE_STATE = {
  dataMode: 'fixture',
  dataAvailability: {
    main: 'fixture',
    thumbnails: 'metadata_only',
    message: 'Fixture mode: real Event Preset data is not required for this skeleton.',
  },
  ratings: [
    {id: 'g', label: 'G'},
    {id: 's', label: 'S'},
    {id: 'q', label: 'Q'},
    {id: 'e', label: 'E'},
  ],
  persons: [
    {id: 'all', label: 'all'},
    {id: 'solo', label: '1girl solo'},
    {id: 'pair', label: '2girls pair'},
    {id: 'group', label: 'group'},
  ],
  categories: [
    {id: 'posture', group: 'GENERAL', label: 'Posture', displayCount: '447k', count: 447000, subcategories: []},
    {id: 'limb-position', group: 'GENERAL', label: 'Limb Position', displayCount: '139k', count: 139000, subcategories: []},
    {id: 'verbs', group: 'GENERAL', label: 'Verbs', displayCount: '74k', count: 74000, subcategories: []},
    {id: 'clothing-action', group: 'GENERAL', label: 'Clothing Action', displayCount: '68k', count: 68000, subcategories: []},
    {id: 'pose', group: 'GENERAL', label: 'Pose', displayCount: '46k', count: 46000, subcategories: []},
    {id: 'body-state', group: 'GENERAL', label: 'Body State', displayCount: '19k', count: 19000, subcategories: []},
    {
      id: 'interaction',
      group: 'GENERAL',
      label: 'Interaction',
      displayCount: '7k',
      count: 32640,
      subcategories: [
        {
          id: 'interaction-hug-embrace',
          label: 'Interaction Hug Embrace',
          count: 18420,
          events: [
            {
              id: 'hug',
              tag: 'hug',
              label: 'hug',
              count: 11880,
              ratings: ['g', 's', 'q'],
              persons: ['all', 'solo', 'pair', 'group'],
              promptAtoms: ['hug', 'embrace', 'close contact'],
              observedCombos: [
                {id: 'hug-close', label: 'close embrace', tags: ['hug', 'arms around body'], count: 4380},
                {id: 'hug-from-behind', label: 'from behind', tags: ['hug from behind', 'looking back'], count: 2110},
                {id: 'comfort-hug', label: 'comfort', tags: ['hug', 'comforting another'], count: 1740},
              ],
              slots: {
                expression: [
                  {id: 'smile', tag: 'smile', count: 2820},
                  {id: 'closed-eyes', tag: 'closed eyes', count: 1190},
                  {id: 'soft-smile', tag: 'soft smile', count: 910},
                ],
                clothing: [
                  {id: 'casual-clothes', tag: 'casual clothes', count: 1760},
                  {id: 'sweater', tag: 'sweater', count: 820},
                  {id: 'school-uniform', tag: 'school uniform', count: 610},
                ],
                characteristic: [
                  {id: 'blush', tag: 'blush', count: 2100},
                  {id: 'looking-at-another', tag: 'looking at another', count: 1340},
                  {id: 'upper-body', tag: 'upper body', count: 960},
                ],
              },
              recommendedTags: [
                {id: 'smile', tag: 'smile', count: 2820},
                {id: 'blush', tag: 'blush', count: 2100},
                {id: 'arms-around-body', tag: 'arms around body', count: 1680},
                {id: 'looking-at-another', tag: 'looking at another', count: 1340},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'hug preview',
                aspectRatio: '3:4',
                accent: '#5cb87a',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'holding-hands',
              tag: 'holding hands',
              label: 'holding hands',
              count: 6540,
              ratings: ['g', 's', 'q'],
              persons: ['all', 'pair', 'group'],
              promptAtoms: ['holding hands', 'interlocked fingers'],
              observedCombos: [
                {id: 'hand-walk', label: 'walking together', tags: ['holding hands', 'walking'], count: 1420},
                {id: 'hand-closeup', label: 'hand close-up', tags: ['holding hands', 'close-up'], count: 980},
              ],
              slots: {
                expression: [
                  {id: 'happy', tag: 'happy', count: 1260},
                  {id: 'smile', tag: 'smile', count: 1120},
                ],
                clothing: [
                  {id: 'dress', tag: 'dress', count: 730},
                  {id: 'casual-clothes', tag: 'casual clothes', count: 620},
                ],
                characteristic: [
                  {id: 'walking', tag: 'walking', count: 1420},
                  {id: 'outdoors', tag: 'outdoors', count: 1180},
                ],
              },
              recommendedTags: [
                {id: 'walking', tag: 'walking', count: 1420},
                {id: 'happy', tag: 'happy', count: 1260},
                {id: 'outdoors', tag: 'outdoors', count: 1180},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'holding hands preview',
                aspectRatio: '3:4',
                accent: '#2878d8',
                source: 'fixture-metadata',
              },
            },
          ],
        },
      ],
    },
    {id: 'personality-state', group: 'GENERAL', label: 'Personality & State', displayCount: '4k', count: 4000, subcategories: []},
    {
      id: 'combat',
      group: 'COMBAT',
      label: 'Combat',
      displayCount: '3k',
      count: 22170,
      subcategories: [
        {
          id: 'combat-ranged-weapon',
          label: 'Ranged Weapon',
          count: 12780,
          events: [
            {
              id: 'holding',
              tag: 'holding',
              label: 'holding',
              count: 1248,
              ratings: ['g', 's', 'q'],
              persons: ['all', 'solo', 'pair', 'group'],
              promptAtoms: ['holding', 'object in hand'],
              observedCombos: [
                {id: 'holding-object', label: 'object in hand', tags: ['holding', 'object in hand'], count: 820},
                {id: 'holding-close', label: 'close-up', tags: ['holding', 'close-up'], count: 410},
              ],
              slots: {
                expression: [
                  {id: 'neutral', tag: 'neutral expression', count: 420},
                  {id: 'focused', tag: 'focused', count: 310},
                ],
                clothing: [
                  {id: 'casual-clothes', tag: 'casual clothes', count: 350},
                  {id: 'gloves', tag: 'gloves', count: 190},
                ],
                characteristic: [
                  {id: 'object-in-hand', tag: 'object in hand', count: 820},
                  {id: 'upper-body', tag: 'upper body', count: 260},
                ],
              },
              recommendedTags: [
                {id: 'object-in-hand', tag: 'object in hand', count: 820},
                {id: 'focused', tag: 'focused', count: 310},
                {id: 'upper-body', tag: 'upper body', count: 260},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'holding preview',
                aspectRatio: '3:4',
                accent: '#2878d8',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'holding-weapon',
              tag: 'holding weapon',
              label: 'holding weapon',
              count: 1012,
              ratings: ['s', 'q', 'e'],
              persons: ['all', 'solo', 'group'],
              promptAtoms: ['holding weapon', 'weapon in hand'],
              observedCombos: [
                {id: 'weapon-ready', label: 'ready stance', tags: ['holding weapon', 'ready stance'], count: 540},
                {id: 'weapon-two-hands', label: 'two-handed grip', tags: ['holding weapon', 'two-handed grip'], count: 330},
              ],
              slots: {
                expression: [
                  {id: 'serious', tag: 'serious', count: 460},
                  {id: 'determined', tag: 'determined', count: 260},
                ],
                clothing: [
                  {id: 'tactical-clothes', tag: 'tactical clothes', count: 520},
                  {id: 'armor', tag: 'armor', count: 230},
                ],
                characteristic: [
                  {id: 'weapon-in-hand', tag: 'weapon in hand', count: 680},
                  {id: 'standing', tag: 'standing', count: 390},
                ],
              },
              recommendedTags: [
                {id: 'weapon-in-hand', tag: 'weapon in hand', count: 680},
                {id: 'serious', tag: 'serious', count: 460},
                {id: 'tactical-clothes', tag: 'tactical clothes', count: 520},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'holding weapon preview',
                aspectRatio: '3:4',
                accent: '#e8a84c',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'holding-gun',
              tag: 'holding gun',
              label: 'holding gun',
              count: 891,
              ratings: ['s', 'q', 'e'],
              persons: ['all', 'solo', 'group'],
              promptAtoms: ['holding gun', 'gun in hand'],
              observedCombos: [
                {id: 'gun-ready', label: 'gun ready', tags: ['holding gun', 'gun in hand'], count: 520},
                {id: 'gun-aim-low', label: 'low ready', tags: ['holding gun', 'low ready'], count: 280},
              ],
              slots: {
                expression: [
                  {id: 'serious', tag: 'serious', count: 410},
                  {id: 'focused', tag: 'focused', count: 220},
                ],
                clothing: [
                  {id: 'gloves', tag: 'gloves', count: 360},
                  {id: 'jacket', tag: 'jacket', count: 210},
                ],
                characteristic: [
                  {id: 'gun-in-hand', tag: 'gun in hand', count: 640},
                  {id: 'trigger-discipline', tag: 'trigger discipline', count: 180},
                ],
              },
              recommendedTags: [
                {id: 'gun-in-hand', tag: 'gun in hand', count: 640},
                {id: 'gloves', tag: 'gloves', count: 360},
                {id: 'focused', tag: 'focused', count: 220},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'holding gun preview',
                aspectRatio: '3:4',
                accent: '#c77dba',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'firing',
              tag: 'firing',
              label: 'firing',
              count: 820,
              ratings: ['s', 'q', 'e'],
              persons: ['all', 'solo', 'group'],
              promptAtoms: ['firing', 'holding gun', 'gun', 'muzzle flash'],
              observedCombos: [
                {
                  id: 'firing-aiming',
                  label: 'aiming and firing',
                  prompt: 'firing, holding gun, gun, muzzle flash, aiming at viewer',
                  tags: ['firing', 'aiming at viewer'],
                  count: 2360,
                },
                {
                  id: 'firing-action',
                  label: 'action shot',
                  prompt: 'firing, action shot, motion blur, muzzle flash, dynamic angle',
                  tags: ['firing', 'motion blur', 'dynamic angle'],
                  count: 1180,
                },
                {
                  id: 'firing-cover',
                  label: 'behind cover',
                  prompt: 'firing, behind cover, smoke, tactical clothes',
                  tags: ['firing', 'cover', 'smoke'],
                  count: 740,
                },
              ],
              slots: {
                expression: [
                  {id: 'serious', tag: 'serious', count: 2140},
                  {id: 'shouting', tag: 'shouting', count: 760},
                  {id: 'determined', tag: 'determined', count: 640},
                ],
                clothing: [
                  {id: 'tactical-clothes', tag: 'tactical clothes', count: 1680},
                  {id: 'armor', tag: 'armor', count: 920},
                  {id: 'gloves', tag: 'gloves', count: 840},
                ],
                characteristic: [
                  {id: 'muzzle-flash', tag: 'muzzle flash', count: 3160},
                  {id: 'smoke', tag: 'smoke', count: 1210},
                  {id: 'dynamic-angle', tag: 'dynamic angle', count: 940},
                ],
              },
              recommendedTags: [
                {id: 'aiming-at-viewer', tag: 'aiming at viewer', count: 2360},
                {id: 'serious', tag: 'serious', count: 2140},
                {id: 'shouting', tag: 'shouting', count: 760},
                {id: 'determined', tag: 'determined', count: 640},
                {id: 'muzzle-flash', tag: 'muzzle flash', count: 3160},
                {id: 'tactical-clothes', tag: 'tactical clothes', count: 1680},
                {id: 'armor', tag: 'armor', count: 920},
                {id: 'gloves', tag: 'gloves', count: 840},
                {id: 'smoke', tag: 'smoke', count: 1210},
                {id: 'dynamic-angle', tag: 'dynamic angle', count: 940},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'firing preview',
                aspectRatio: '16:9',
                accent: '#e8a84c',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'railgun-misaka',
              tag: 'railgun (misaka mikoto)',
              label: 'railgun (misaka mikoto)',
              count: 135,
              ratings: ['s', 'q'],
              persons: ['all', 'solo'],
              promptAtoms: ['railgun', 'electricity', 'coin'],
              observedCombos: [
                {id: 'railgun-electric', label: 'electric arc', tags: ['railgun', 'electricity'], count: 92},
              ],
              slots: {
                expression: [{id: 'confident', tag: 'confident', count: 70}],
                clothing: [{id: 'school-uniform', tag: 'school uniform', count: 88}],
                characteristic: [{id: 'electricity', tag: 'electricity', count: 104}],
              },
              recommendedTags: [
                {id: 'electricity', tag: 'electricity', count: 104},
                {id: 'confident', tag: 'confident', count: 70},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'railgun preview',
                aspectRatio: '16:9',
                accent: '#9d8bff',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'at-gunpoint',
              tag: 'at gunpoint',
              label: 'at gunpoint',
              count: 96,
              ratings: ['q', 'e'],
              persons: ['all', 'solo', 'pair'],
              promptAtoms: ['at gunpoint', 'threatened'],
              observedCombos: [
                {id: 'gunpoint-viewer', label: 'at viewer', tags: ['at gunpoint', 'gun pointed at viewer'], count: 46},
              ],
              slots: {
                expression: [{id: 'scared', tag: 'scared', count: 42}],
                clothing: [{id: 'casual-clothes', tag: 'casual clothes', count: 32}],
                characteristic: [{id: 'gun-pointed', tag: 'gun pointed at viewer', count: 46}],
              },
              recommendedTags: [
                {id: 'scared', tag: 'scared', count: 42},
                {id: 'gun-pointed', tag: 'gun pointed at viewer', count: 46},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'gunpoint preview',
                aspectRatio: '3:4',
                accent: '#d86c6c',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'aiming',
              tag: 'aiming',
              label: 'aiming',
              count: 84,
              ratings: ['s', 'q', 'e'],
              persons: ['all', 'solo', 'group'],
              promptAtoms: ['aiming', 'holding weapon'],
              observedCombos: [
                {id: 'aiming-viewer', label: 'aiming at viewer', tags: ['aiming', 'aiming at viewer'], count: 52},
              ],
              slots: {
                expression: [{id: 'focused', tag: 'focused', count: 39}],
                clothing: [{id: 'gloves', tag: 'gloves', count: 28}],
                characteristic: [{id: 'aiming-at-viewer', tag: 'aiming at viewer', count: 52}],
              },
              recommendedTags: [
                {id: 'aiming-at-viewer', tag: 'aiming at viewer', count: 52},
                {id: 'focused', tag: 'focused', count: 39},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'aiming preview',
                aspectRatio: '16:9',
                accent: '#5cb87a',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'reloading',
              tag: 'reloading',
              label: 'reloading',
              count: 71,
              ratings: ['s', 'q', 'e'],
              persons: ['all', 'solo', 'group'],
              promptAtoms: ['reloading', 'holding gun'],
              observedCombos: [
                {id: 'reload-magazine', label: 'magazine reload', tags: ['reloading', 'magazine'], count: 44},
              ],
              slots: {
                expression: [{id: 'focused', tag: 'focused', count: 34}],
                clothing: [{id: 'tactical-clothes', tag: 'tactical clothes', count: 29}],
                characteristic: [{id: 'magazine', tag: 'magazine', count: 44}],
              },
              recommendedTags: [
                {id: 'magazine', tag: 'magazine', count: 44},
                {id: 'focused', tag: 'focused', count: 34},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'reloading preview',
                aspectRatio: '3:4',
                accent: '#e8a84c',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'looking-at-viewer',
              tag: 'looking at viewer',
              label: 'looking at viewer',
              count: 672,
              ratings: ['g', 's', 'q', 'e'],
              persons: ['all', 'solo', 'pair', 'group'],
              promptAtoms: ['looking at viewer'],
              observedCombos: [
                {id: 'viewer-direct', label: 'direct gaze', tags: ['looking at viewer', 'direct gaze'], count: 420},
              ],
              slots: {
                expression: [{id: 'neutral', tag: 'neutral expression', count: 240}],
                clothing: [{id: 'casual-clothes', tag: 'casual clothes', count: 210}],
                characteristic: [{id: 'direct-gaze', tag: 'direct gaze', count: 420}],
              },
              recommendedTags: [
                {id: 'direct-gaze', tag: 'direct gaze', count: 420},
                {id: 'neutral', tag: 'neutral expression', count: 240},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'looking preview',
                aspectRatio: '3:4',
                accent: '#2878d8',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'standing',
              tag: 'standing',
              label: 'standing',
              count: 611,
              ratings: ['g', 's', 'q', 'e'],
              persons: ['all', 'solo', 'pair', 'group'],
              promptAtoms: ['standing'],
              observedCombos: [
                {id: 'standing-full-body', label: 'full body', tags: ['standing', 'full body'], count: 320},
              ],
              slots: {
                expression: [{id: 'neutral', tag: 'neutral expression', count: 220}],
                clothing: [{id: 'casual-clothes', tag: 'casual clothes', count: 260}],
                characteristic: [{id: 'full-body', tag: 'full body', count: 320}],
              },
              recommendedTags: [
                {id: 'full-body', tag: 'full body', count: 320},
                {id: 'casual-clothes', tag: 'casual clothes', count: 260},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'standing preview',
                aspectRatio: '3:4',
                accent: '#5cb87a',
                source: 'fixture-metadata',
              },
            },
            {
              id: 'sitting',
              tag: 'sitting',
              label: 'sitting',
              count: 387,
              ratings: ['g', 's', 'q', 'e'],
              persons: ['all', 'solo', 'pair', 'group'],
              promptAtoms: ['sitting'],
              observedCombos: [
                {id: 'sitting-chair', label: 'on chair', tags: ['sitting', 'chair'], count: 180},
              ],
              slots: {
                expression: [{id: 'relaxed', tag: 'relaxed', count: 160}],
                clothing: [{id: 'casual-clothes', tag: 'casual clothes', count: 190}],
                characteristic: [{id: 'chair', tag: 'chair', count: 180}],
              },
              recommendedTags: [
                {id: 'chair', tag: 'chair', count: 180},
                {id: 'relaxed', tag: 'relaxed', count: 160},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'sitting preview',
                aspectRatio: '3:4',
                accent: '#c77dba',
                source: 'fixture-metadata',
              },
            },
          ],
        },
      ],
    },
    {id: 'exposure-nudity', group: 'NSFW', label: 'Exposure & Nudity', displayCount: '28k', count: 28000, subcategories: []},
    {id: 'sex-acts', group: 'NSFW', label: 'Sex Acts', displayCount: '24k', count: 24000, subcategories: []},
    {
      id: 'daily-life',
      group: 'GENERAL',
      label: 'Daily Life',
      displayCount: '15k',
      count: 14510,
      subcategories: [
        {
          id: 'daily-life-food',
          label: 'Food And Drink',
          count: 14510,
          events: [
            {
              id: 'drinking-tea',
              tag: 'drinking tea',
              label: 'drinking tea',
              count: 4120,
              ratings: ['g', 's'],
              persons: ['all', 'solo', 'pair'],
              promptAtoms: ['drinking tea', 'teacup', 'relaxed'],
              observedCombos: [
                {id: 'tea-window', label: 'near window', tags: ['drinking tea', 'window'], count: 880},
                {id: 'tea-cafe', label: 'cafe table', tags: ['drinking tea', 'cafe'], count: 760},
              ],
              slots: {
                expression: [
                  {id: 'relaxed', tag: 'relaxed', count: 1200},
                  {id: 'gentle-smile', tag: 'gentle smile', count: 840},
                ],
                clothing: [
                  {id: 'cardigan', tag: 'cardigan', count: 520},
                  {id: 'long-sleeves', tag: 'long sleeves', count: 480},
                ],
                characteristic: [
                  {id: 'steam', tag: 'steam', count: 960},
                  {id: 'sitting', tag: 'sitting', count: 1280},
                ],
              },
              recommendedTags: [
                {id: 'steam', tag: 'steam', count: 960},
                {id: 'gentle-smile', tag: 'gentle smile', count: 840},
                {id: 'cafe', tag: 'cafe', count: 760},
              ],
              thumbnail: {
                status: 'metadata_only',
                label: 'drinking tea preview',
                aspectRatio: '3:4',
                accent: '#c77dba',
                source: 'fixture-metadata',
              },
            },
          ],
        },
      ],
    },
  ],
  selected: {
    ratingId: 's',
    personId: 'solo',
    search: 'holding',
    categoryId: 'combat',
    subcategoryId: 'combat-ranged-weapon',
    eventId: 'firing',
    comboId: 'firing-aiming',
    recommendedTagIds: ['aiming-at-viewer', 'muzzle-flash'],
  },
};

export function createEventPresetFixtureState() {
  return JSON.parse(JSON.stringify(EVENT_PRESET_FIXTURE_STATE));
}
